\documentclass[9pt,aspectratio=169]{beamer}
\geometry{paperwidth=160mm,paperheight=92mm}
% for themes matrix: http://www.hartwork.org/beamer-theme-matrix/
%\mode<presentation>{ \usetheme{Pittsburgh}\usecolortheme{seahorse}\setbeamertemplate{blocks}[rounded][shadow=true] }
%\mode<presentation>{ \usetheme{Singapore}\usecolortheme{crane}\setbeamertemplate{blocks}[rounded][shadow=true] }
%\mode<presentation>{ \usetheme{CambridgeUS}\usecolortheme{crane}\setbeamertemplate{blocks}[rounded][shadow=true] }
%\mode<presentation>{ \usetheme{Warsaw}\usecolortheme{beaver}\setbeamertemplate{blocks}[rounded][shadow=true] }
%\mode<presentation>{ \usetheme{Pittsburgh}\usecolortheme{wolverine}\setbeamertemplate{blocks}[rounded][shadow=true] }
\mode<presentation>{ \usetheme{CambridgeUS}\usecolortheme{seagull}\setbeamertemplate{blocks}[rounded][shadow=true]\setbeamertemplate{items}[circle]}
%\mode<presentation>{ \usetheme{boxes} }

% for help on beamer, see e.g.
% http://heather.cs.ucdavis.edu/~matloff/beamer.html
% wget http://heather.cs.ucdavis.edu/~matloff/BeamerTour.tex
%
% beamer with 2-page sweave & code:
% http://stackoverflow.com/questions/6964750/two-column-beamer-sweave-slide-with-grid-graphic
%

%2FIX: put a header here.

\typeout{-- sharpe slide show}
\typeout{-- NC 2013-2021 s.e.p.}

%preamble%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%FOLDUP

%\usepackage{psfig}\psfull
%\usepackage{graphicx,epsfig,psfrag}
\usepackage{graphicx}
\usepackage{subfigure}
%\graphicspath{{figs/}}

%\PassOptionsToPackage{hyphens}{url}\usepackage{hyperref}
%\usepackage{hyperref}
% this pukes:
\usepackage[square,numbers]{natbib}
% http://superuser.com/a/63094/60965
% this does not:
%\usepackage[natbib=true, bibstyle=authoryear, citestyle=authoryear-comp]{biblatex}
% ok, fuccccck that.

%for pretty printing code;
\usepackage{listings}
\lstset{frame=topline,float=tbph,tabsize=2,numbers=left}

% how to turn off roman numbers in the frame titles.
\setbeamertemplate{frametitle continuation}{}
%compactitem and such:
%\usepackage[newitem,newenum,increaseonly]{paralist}
%\usepackage{enumitem}
%\renewlist{itemize}{itemize}{6}
%\renewlist{enumerate}{enumerate}{6}
%\setlist{enumerate}

\usepackage[notheorems]{SharpeR}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% commands specific to this paper:%FOLDUP
%\newcommand{\madnesspack}{\CRANpkg{madness}\xspace}
\newcommand{\sharper}{\CRANpkg{SharpeR}\xspace}
%\newcommand{\madobj}{\Robject{madness}\xspace}
\providecommand{\RMAT}[1][{}]{\MtxUL{R}{#1}{}}
\providecommand{\RHAT}[1][{}]{\MtxUL{\hat{R}}{#1}{}}
\providecommand{\AAA}[1][{}]{\MtxUL{A}{#1}{}}
\providecommand{\bbb}[1][{}]{\vectUL{b}{#1}{}}
\providecommand{\etav}[1][{}]{\vectUL{\eta}{#1}{}}
\providecommand{\yvec}[1][{}]{\vectUL{y}{#1}{}}
\providecommand{\Vfunc}[1]{\mathUL{\mathcal{V}}{#1}{}}
\providecommand{\Vmin}{\Vfunc{-}}
\providecommand{\Vmax}{\Vfunc{+}}

\providecommand{\makerho}[3][{\vone}]{{#3}\,\eye + {#2}\wrapParens{\ogram{#1}}}
\providecommand{\minusrho}[3][{\vone}]{{#3}\,\eye - {#2}\wrapParens{\ogram{#1}}}
\providecommand{\smashrho}[4][{\vone}]{{#3}\,\eye {#2}\frac{\wrapParens{\ogram{#1}}}{#4}}
\providecommand{\rhoR}{\makerho{\rho}{\wrapParens{1-\rho}}}
\providecommand{\trbasev}[1][]{\vectUL{e}{\trsym}{#1}}

% "asymptotically normal"
%\providecommand{\asymto}[3]{\sqrt{\ssiz}\wrapParens{#1 - #2}\rightsquigarrow \normlaw{0,#3}}
%\providecommand{\vasymto}[3]{\asymto{\fvech{#1}}{\fvech{#2}}{#3}}
%UNFOLD

\usepackage{xcolor}
\fboxsep=1.5mm%padding thickness
\fboxrule=2pt%border thickness

%% for colored boxes!
% tikz? see http://tex.stackexchange.com/a/55217/2530%FOLDUP
\usepackage{tikz}
\usetikzlibrary{arrows,shapes}
\tikzstyle{every picture}+=[remember picture]
\tikzstyle{na} = [baseline=-.5ex]

% and stolen from http://tex.stackexchange.com/a/75255/2530
\usetikzlibrary{calc}
% put color to \boxed math command
%\newcommand*{\boxcolor}{orange}
\newcommand*{\boxcolor}{red}
\newcommand*{\poboxcolor}{gray!50}
\newcommand*{\ULcol}{red!30}
\newcommand*{\ODcol}{blue!30}
\newcommand*{\LRcol}{yellow!30}
\makeatletter
\renewcommand{\boxed}[1]{\textcolor{\boxcolor}{%
\tikz[baseline={([yshift=-1ex]current bounding box.center)}] \node [rectangle, minimum width=1ex,rounded corners,draw] {\normalcolor\m@th$\displaystyle#1$};}}
\providecommand{\poboxed}[1]{\textcolor{\poboxcolor}{%
\tikz[baseline={([yshift=-1ex]current bounding box.center)}] \node [rectangle, minimum width=1ex,rounded corners,draw] {\normalcolor\m@th$\displaystyle#1$};}}
\providecommand{\colorboxed}[2]{\tikz[baseline]{\node[fill=#1,anchor=base,rounded corners=2pt] {#2}; }}
% color, tag, content:
\providecommand{\nodeboxed}[3]{\tikz[baseline]{ \node[fill=#1,anchor=base,rounded corners=2pt] #2 {#3};}}

\providecommand{\redbox}[2]{\nodeboxed{\ULcol}{#2}{$#1$}}
\makeatother

% "asymptotically normal"
\providecommand{\asymto}[3]{\sqrt{\ssiz}\wrapParens{#1 - #2}\rightsquigarrow \normlaw{0,#3}}
\providecommand{\vasymto}[3]{\asymto{\fvech{#1}}{\fvech{#2}}{#3}}
\providecommand{\Ugly}{\Mtx{U}}

%UNFOLD

    \usepackage{color} % Allow colors to be defined
    \definecolor{linkblue}{rgb}{0,.225,.995}
    \definecolor{darkorange}{rgb}{.71,0.21,0.01}
    \definecolor{darkgreen}{rgb}{.12,.54,.11}
% Prevent overflowing lines due to hard-to-break entities
\sloppy 
% Setup hyperref package
\hypersetup{
	breaklinks=true,  % so long urls are correctly broken across lines
	colorlinks=true,
	urlcolor=linkblue,
	linkcolor=darkorange,
	citecolor=darkgreen,
	}
%UNFOLD

% latex shortcuts%FOLDUP
\usepackage[notheorems]{SharpeR}
% see discussion here:
% http://tex.stackexchange.com/questions/4216/how-to-typeset-correctly
%\renewcommand{\defeq}{:=}
\renewcommand{\defeq}{\mathrel{\mathop:}=}
\renewcommand{\fvola}[1][]{\mathSUB{w}{#1}}
%\renewcommand{\defeq}{\stackrel{\text{\tiny def}}{=}}
%\usepackage[commands,shortcuts]{sepmath}
%\input{sharpe_shortcuts.tex}

%for pretty printing code;
%\usepackage{listings}
%UNFOLD

\title[Inference on the asset with maximal Sharpe]{Inference on the asset with maximal Sharpe ratio}%FOLDUP
%\subtitle{(Multivariate Automatic Differentiation)}
%\institute{Gilgamath Consulting}
\subject{Financial Statistics}
\keywords{R, Statistics, Quantitative finance, Sharpe ratio}
\author[Steven Pav]
{%
  \texorpdfstring{
	Steven E. Pav \\
	\href{mailto:steven@gilgamath.com}{\email{steven@gilgamath.com}}
	%\href{mailto:steven@sharperat.io}{\email{steven@sharperat.io}}
	%\href{mailto:steven.e.pav@bofa.com}{\email{Steven Pav (CRMD)}}
	}{Steven Pav}
}
\date{\today}
%\date{May 20, 2016}
%(@shabbychef)\\
%http://tinyurl.com/RinF2012-spav}
%UNFOLD

% have this if you'd like a recurring outline
%\AtBeginSection[]  % "Beamer, do the following at the start of every section"
%{
%\begin{frame}<beamer> 
%\frametitle{Outline} % make a frame titled "Outline"
%\tableofcontents[currentsection]  % show TOC and highlight current section
%\end{frame}
%}
%\providecommand{\substext}{\quad...\,require(shiny) \&\& runGist("75e1066b3db6b0f9e981")}
%\providecommand{\substext}{\quad\quad\quad\quad\quad shiny::runGist("75e1066b3db6b0f9e981")}
%\providecommand{\substext}{\quad\quad\quad\quad\quad install.packages('madness')}
\providecommand{\substext}{}

% cf https://tex.stackexchange.com/a/12551/2530
\newenvironment{centblock}[2]{\begin{center}\begin{minipage}{#1}\begin{block}{#2}}{%
\end{block}\end{minipage}\end{center}}


\begin{document}

%% preamble%FOLDUP
%<<'knitr_preamble',echo=FALSE,cache=FALSE,warning=FALSE,message=FALSE>>=
%library(knitr)

%# set the knitr options ... for everyone!
%# if you unset this, then vignette build bonks. oh, joy.
%#opts_knit$set(progress=TRUE)
%opts_knit$set(eval.after='fig.cap')
%# for a package vignette, you do want to echo.
%# opts_chunk$set(echo=FALSE,warning=FALSE,message=FALSE)
%opts_chunk$set(warning=FALSE,message=FALSE)
%#opts_chunk$set(results="asis")
%mybit <- 'rfin2019_show_'
%opts_chunk$set(cache=TRUE,cache.path=file.path("cache",mybit))

%#opts_chunk$set(fig.path="figure/",dev=c("pdf","cairo_ps"))
%opts_chunk$set(fig.path=file.path("figure",mybit),dev=c("pdf"))
%opts_chunk$set(fig.width=5,fig.height=4,dpi=64)

%# doing this means that png files are made of figures;
%# the savings is small, and it looks like shit:
%#opts_chunk$set(fig.path="figure/",dev=c("png","pdf","cairo_ps"))
%#opts_chunk$set(fig.width=4,fig.height=4)
%# for figures? this is sweave-specific?
%#opts_knit$set(eps=TRUE)

%# this would be for figures:
%#opts_chunk$set(out.width='.8\\textwidth')
%# for text wrapping:
%options(width=86,digits=2)
%#opts_chunk$set(tidy=FALSE,tidy.opts=list(width.cutoff=54,keep.blank.line=FALSE))
%opts_chunk$set(size="small")
%#opts_chunk$set(tidy=TRUE,tidy.opts=list(width.cutoff=50,keep.blank.line=TRUE))
%opts_chunk$set(tidy=FALSE)

%# see also http://yihui.name/knitr/options#chunk_options
%opts_chunk$set(highlight=TRUE)
%#other options are 
%# "normalsize", "tiny", "scriptsize", "footnotesize"
%# "small", "large", "Large", "LARGE", "huge", "Huge"
%#
%# footnotesize seems to be the same as small, and
%# the same as the default? or was there caching going on there?
%opts_chunk$set(size="footnotesize")

%## cf https://github.com/yihui/knitr-examples/blob/master/044-size.Rnw
%#knit_hooks$set(size = function(before, options, envir) {
%#  # bring back the size environment when results='asis'
%#  if (options$results != 'asis') return()
%#  paste('\\end{kframe}',
%#        sprintf(if (before) '\\begin{%s}' else '\\end{%s}', options$size),
%#        '\\begin{kframe}', sep = '')
%#})
%##library(xtable)
%@
%%UNFOLD
% knitr setup%FOLDUP

<<'preamble', include=FALSE, warning=FALSE, message=FALSE>>=
library(knitr)

# set the knitr options ... for everyone!
# if you unset this, then vignette build bonks. oh, joy.
#opts_knit$set(progress=TRUE)
opts_knit$set(eval.after='fig.cap')
opts_chunk$set(warning=FALSE,message=FALSE)
#opts_chunk$set(results="asis")
mybit <- 'sshow_'
opts_chunk$set(cache=TRUE,cache.path=file.path("cache",mybit))

#opts_chunk$set(fig.path="figure/",dev=c("pdf","cairo_ps"))
opts_chunk$set(fig.path=file.path("figure",mybit),dev=c("pdf"))
opts_chunk$set(dpi=400,
							 fig.width=0.975*10,
							 fig.height=0.4*10,
							 out.width="0.975\\textwidth",
							 out.height="0.4\\textwidth",
							 fig.align='center')

# doing this means that png files are made of figures;
# the savings is small, and it looks like shit:
#opts_chunk$set(fig.path="figure/",dev=c("png","pdf","cairo_ps"))
#opts_chunk$set(fig.width=4,fig.height=4)
# for figures? this is sweave-specific?
#opts_knit$set(eps=TRUE)

# this would be for figures:
#opts_chunk$set(out.width='.8\\textwidth')
# for text wrapping:
options(width=64,digits=2)
opts_chunk$set(size="small")
opts_chunk$set(tidy=TRUE,tidy.opts=list(width.cutoff=50,keep.blank.line=TRUE))

compile.time <- Sys.time()

suppressMessages({
	require(dplyr)
	require(tidyr)
	require(tibble)
	require(ggplot2)
	library(SharpeR)
	library(gghighlight)
	sal <- dplyr::select
	filta <- dplyr::filter
  require(future,quietly=TRUE)
  require(future.apply,quietly=TRUE)
})

#gen_norm <- rnorm
#lseq <- function(from,to,length.out) { exp(seq(log(from),log(to),length.out = length.out)) }
@
<<'plot_options',include=FALSE,warning=FALSE,message=FALSE>>=
theme_set(theme_minimal())
# theme_set(theme_minimal(base_size=12))
theme_update(legend.position="bottom")

VIRIDIS_COLOR_OPTION <- 'plasma'
if (require(viridis,quietly=TRUE)) {
  scale_colour_discrete <- function(...) {
    require(viridis,quietly=TRUE)
    scale_color_viridis(discrete=TRUE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
  scale_fill_discrete <- function(...) {
    require(viridis,quietly=TRUE)
    scale_fill_viridis(discrete=TRUE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
  # wait, can I also default for continuous cases?
  scale_colour_continuous <- function(...) {
    require(viridis,quietly=TRUE)
    scale_color_viridis(discrete=FALSE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
  scale_fill_continuous <- function(...) {
    require(viridis,quietly=TRUE)
    scale_fill_viridis(discrete=FALSE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
}
@
%UNFOLD

\begin{frame}
\titlepage
\end{frame}

%see http://robfelty.com/2008/09/22/beamer-fragile-frames 
%for fragile and verbatim
% and another warning:
% you cannot put folds around the begin/end{frame} when
% it is fragile. o/w the whole thing pukes. really. really.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Background}%FOLDUP

\subsection{The \txtSR}
%\subsection{\substext}

% a common problem %FOLDUP
\begin{frame}[allowframebreaks]{The \txtSR}
%Consider the quantitative investment problem:\\
\begin{centblock}{0.94\textwidth}{The Quantitative Investment Problem}
%\begin{quote}
Given some assets,
how do you select one to invest in,
based only on the distribution of returns?
%\end{quote}
\end{centblock}
%This problem has two forms:
\begin{enumerate}
\item How would you invest if you knew the population distribution (mean, variance, \etc) of returns? 
\item How would you invest if you have to estimate the distribution?
\end{enumerate}
\citet{Sharpe:1966} proposed a ``reward-to-variability'' ratio to compare
mutual funds:
\begin{equation*}
\boxed{
\ssr = \frac{\smu}{\ssig}
}
\end{equation*}
A heuristic based on investors preference for higher returns and lower `risk'.\\
Proposed earlier by \citet{roySafety1952}:
by Chebyshev's inequality,
\begin{equation*}
\boxed{
\probof{\mbox{returns} < 0} \le \wrapParens{\frac{\pmu}{\psig}}^{-2}
}
\end{equation*}
So optimize $\fracc{\pmu}{\psig}$ to minimize probability of a loss.\\

%Risk-adverse investors align their preferences with \emph{stochastic dominance}.
%\begin{itemize}
%\item A collection of partial orders on probability distributions.
%\item $A$ (first order) stochastically dominates $B$ if $\Pof{A > x} \ge \Pof{B > x}$ for all $x$.
%\item Generally these prefer higher mean returns, and lower variance of returns.
%\item Stochastic dominance does not form a total order: given two distributions
	%neither may dominate the other.
%\end{itemize}
%Quantitative investment requires a total order on investments: a way to compare any two investments.

%\framebreak
\end{frame}
\begin{frame}[allowframebreaks]{Mean Variance Tradeoff}

Risk adverse investors prefer higher mean return and lower variance of returns:

<<'ret_thing',echo=FALSE,eval=TRUE,cache=TRUE,fig.width=0.75*14,fig.height=0.42*14,out.width="0.75\\textwidth",out.height="0.42\\textwidth">>=
# return n returns with a fixed sample mean and sample standard deviation:
fixx <- function(x,mu,sig) {
	z <- (x - mean(x)) / sd(x)
	z * sig + mu 
}
nday <- 252*4
#params <- crossing(tibble(mu=seq(0.06,0.24,length.out=4)/252),
									 #tibble(sig=sqrt(seq(0.01,0.07,length.out=4)/252)))
params <- crossing(tibble(mu=seq(0.08,0.24,length.out=3)/252),
									 tibble(sig=sqrt(seq(0.01,0.09,length.out=3)/252)))
set.seed(5678)
rets <- params %>%
	group_by(mu,sig) %>%
		summarize(arx=list(fixx(rnorm(nday,mean=mu,sd=sig),mu=mu,sig=sig))) %>%
	ungroup() %>%
	unnest(arx) %>%
	group_by(mu,sig) %>%
		mutate(value=exp(cumsum(arx))) %>%
		mutate(day=seq_len(n())) %>%
	ungroup()

ph <- rets %>% 
	mutate(mean=252*mu,variance=252*sig^2) %>%
	ggplot(aes(day,value,group=interaction(mean,variance))) + 
	geom_line(color='red') + 
	facet_grid(mean~variance,labeller=label_both,scales='fixed') + 
	#theme_void() + 
	labs(x='days',
			 y='value',
			 title='Hypothetical investments')
print(ph)
@
\end{frame}
\section{Overfitting}
\subsection{Problem Formulation}
\begin{frame}[allowframebreaks]{Overfitting}

\begin{center}
		%\includegraphics[scale=0.35]{extra/xkcd_1570.png}
		\includegraphics[width=0.5\linewidth]{media/syllogism.jpg}
\end{center}

Overfitting is a serious problem in quantitative investing:
\begin{itemize}
	\item Profitable trading strategies are probably rare.
	\item Availability of data and computing power enable us to consider thousands of strategies.
	\item Long historical data may not be available or relevant: ``wide data''.
	\item You collect out-of-sample data very slowly: one day per day.
\end{itemize}

\end{frame}

\begin{frame}[allowframebreaks]{The Overfitting Problem}

Suppose you observe $\nstrat$ strategies' historical returns, with
Sharpe ratios 
$$
\ssr[(1)] \le \ssr[(2)] \le \ldots \le \ssr[(\nstrat)]
$$
What can we say about the strategy associated with \ssr[(\nstrat)]?

<<'pick_best',echo=FALSE,eval=TRUE,cache=TRUE,fig.width=0.67*14,fig.height=0.31*14,out.width="0.67\\textwidth",out.height="0.31\\textwidth">>=
nstrat <- 100
nday <- 252*4
sg <- 0.013
sr <- 1 / sqrt(252)
mu <- sg*sr

set.seed(1234)
foo <- tibble(rets=rnorm(nday*nstrat,mean=mu,sd=sg)) %>%
	mutate(strat=rep(1:nstrat,nday)) %>%
	group_by(strat) %>%
		mutate(day=seq_len(n())) %>%
	ungroup() %>%
	arrange(strat,day) %>%
	group_by(strat) %>%
		mutate(mtm=exp(cumsum(rets))) %>%
	ungroup() %>%
	arrange(strat,day) %>%
	group_by(strat) %>%
		mutate(sr=sqrt(252) * mean(rets) / sd(rets)) %>%
	ungroup() %>%
	mutate(isbest=sr==max(sr))

ph <- foo %>% 
	filta(!isbest) %>%
	ggplot(aes(day,mtm,group=strat)) + 
	#geom_line(aes(color=isbest)) + 
	geom_line(color='grey40',alpha=0.6) +
	geom_line(data=foo %>% filta(isbest),color='red') + 
	scale_y_log10() + 
	#theme_void() + 
	labs(x='days',
			 y='value',
			 title='Hypothetical investments')
print(ph)
@




<<'show_mtms',echo=FALSE,eval=FALSE,cache=TRUE,fig.width=0.75*10,fig.height=0.3*10,out.width="0.75\\textwidth",out.height="0.3\\textwidth">>=
nday <- 252*4
sigx <- 0.010
sigy <- 2.9*sigx
mu <- (1.4 / sqrt(252)) * sigx
#set.seed(1309)
set.seed(1429)
dat <- tibble::tibble(x=rnorm(nday,mean=mu,sd=sigx),
											y=rnorm(nday,mean=mu,sd=sigy)) %>%
	mutate(x=x + mean(y) - mean(x)) %>%
	mutate(A=exp(cumsum(x)),B=exp(cumsum(y))) %>%
	mutate(day=seq_len(n())) %>%
	select(day,A,B) %>%
	tidyr::gather(key=investment,value=value,A,B)
	

ph <- dat %>%
	ggplot(aes(day,value,color=investment)) +
	geom_line() + 
	labs(x='days',
			 y='value',
			 title='two hypothetical investments')
print(ph)
@

\end{frame}
%UNFOLD
%UNFOLD


\subsection{Inference on Asset with Maximal \txtSNR}
%\subsection{\substext}

% a common problem %FOLDUP
\begin{frame}{Inference on the Asset with Maximal Signal-Noise Ratio}

%Two approaches to the problem:\\
{\bf Classical Multiple Hypothesis Testing (MHT)}\hspace{2mm}\\
	\begin{itemize}
		\item
Test \emph{all} strategies, correcting for multiple tests:
%Test the hypothesis
\begin{equation}
\label{hyp:max_snr_uit}
\Hyp[0] : \forall i\,\psnr[i] = \psnr[0]\quad\mbox{versus}\quad \Hyp[1] : \exists i: \psnr[i] > \psnr[0].
\end{equation}
		\item
			Classically via the Bonferroni correction: perform $\nstrat$ tests at the $\alpha/\nstrat$ level.
		\item
			Advances by \citet{White:2000} (bootstrapping) and \citet{Hansen:2005} (Studentizing, ``loglog trick'').
	\end{itemize}
MHT has limitations:
\begin{itemize}
	\item If you invest in strategy \nstrat, you are not interested in strategies $1,2,\ldots,\nstrat -1$.
	\item Correlation among strategy returns can reduce power.
	\item Bootstrapping will not scale to 1000's of strategies.
\end{itemize}

{\bf Conditional Inference}\\
\begin{itemize}
	\item
Test \emph{only the selected strategy}:
%\begin{equation}
  %\label{hyp:snr_conditional_test}
  %\Hyp[0] : \acondb{\psnr[(\nstrat)] = \psnr[0]}{\ssr \ge \psnr[1]}\quad\mbox{versus}\quad \Hyp[1] : \psnr[(\nstrat)] > \psnr[0],
%\end{equation}
\begin{equation}
  \label{hyp:max_snr_conditional}
  \Hyp[0] : \psnr[(\nstrat)] = \psnr[0]\quad\mbox{versus}\quad \Hyp[1] : \psnr[(\nstrat)] > \psnr[0].
\end{equation}
\item
	No classical formulation in statistics.
\item
	Should we be concerned with $\psnr[(\nstrat-1)]$?
\end{itemize}
\end{frame}
%UNFOLD
%UNFOLD

\section{MHT}
\subsection{Multiple Hypothesis Testing Correction}

\begin{frame}[fragile]{Correlated Returns}
Often you are testing variations on a strategy, causing correlated returns.\\
The \txtSRs are correlated as well.
<<'pick_best_rho',echo=FALSE,eval=TRUE,cache=TRUE,fig.width=0.67*14,fig.height=0.31*14,out.width="0.67\\textwidth",out.height="0.31\\textwidth">>=
nstrat <- 100
nday <- 252*4
sg <- 0.013
sr <- 1 / sqrt(252)
mu <- sg*sr
rho <- 0.9

set.seed(5678)
foo <- tibble(rets=rnorm(nday*nstrat,mean=mu,sd=sg)) %>%
	mutate(strat=rep(1:nstrat,nday)) %>%
	group_by(strat) %>%
		mutate(day=seq_len(n())) %>%
	ungroup() %>%
	arrange(strat,day) %>%
	group_by(day) %>%
		mutate(avg=first(rets)) %>%
	ungroup() %>%
	mutate(rets=rho*avg + sqrt(1-rho^2)*rets) %>%
	group_by(strat) %>%
		mutate(mtm=exp(cumsum(rets))) %>%
	ungroup() %>%
	arrange(strat,day) %>%
	group_by(strat) %>%
		mutate(sr=sqrt(252) * mean(rets) / sd(rets)) %>%
	ungroup() %>%
	mutate(isbest=sr==max(sr))

ph <- foo %>% 
	filta(!isbest) %>%
	ggplot(aes(day,mtm,group=strat)) + 
	#geom_line(aes(color=isbest)) + 
	geom_line(color='grey40',alpha=0.4) +
	geom_line(data=foo %>% filta(isbest),color='red') + 
	scale_y_log10() + 
	#theme_void() + 
	labs(x='days',
			 y='value',
			 title='Hypothetical investments')
print(ph)
@
\end{frame}

% bonferroni
\begin{frame}[fragile]{Bonferroni on Correlated Returns}
When \RMAT is correlation of returns, then
\begin{equation}
\svsr \approx 
%\normlaw{\pvsnr,\oneby{\ssiz}\wrapParens{\RMAT +
	%\frac{1}{2} \Mdiag{\pvsnr} \wrapParens{\RMAT\hadm\RMAT} \Mdiag{\pvsnr}}}.
%\label{eqn:apx_srdist_elliptical}
\normlaw{\pvsnr,\oneby{\ssiz}\RMAT}.
\label{eqn:even_more_apx_srdist_elliptical}
\end{equation}
	\vspace{-5mm}
\begin{itemize}
	\item
		For rank one correlation model $\RMAT=\rhoR$, 
		under the null
$\Hyp[0]:\pvsnr=\psnr[0]\vone$, 
$$
\svsr - \psnr[0]\vone \sim \normlaw{\vzero,\makerho{a_2}{a_1}}.
$$
\item
The covariance is ``order preserving.'' 
The \kth{\nstrat} element of the following is the largest:
$$
\wrapParens{\makerho{a_2}{a_1}}^{-\halff}\wrapParens{\svsr - \psnr[0]\vone} \sim \normlaw{\vzero,\eye}.
$$
\item
	The rank one model is good enough by Slepian's Lemma: take $\rho$ to be minimum correlation.
\item
	\citet{Hansen:2005} showed you don't have to count all \nstrat strategies.\\
		Can ignore the duds if you define the cutoff properly.
\end{itemize}

\end{frame}


%% you could just %FOLDUP
%\begin{frame}[fragile]{You could just ...}
%Use a simple correction for Multiple Hypothesis Testing (MHT):\cite{lopezdeprado2018false}

%\begin{itemize}
%\item Assume the $\ssr[i]$ are independent, and all $\psnr[i]$ are equal (to zero, say).
%\item Use MHT correction, like Bonferroni, when hypothesis testing.
%\item Or use beta correction for inference:
%\end{itemize}
%\vspace{-4mm}
%<<'beta_correction',echo=TRUE,eval=FALSE,cache=TRUE>>=
%# cdf & qtile, max of np independent SRs, SNR=zeta
%pmaxsr <- function(q,df,np,zeta=0,ope=1) {
	%pv <- SharpeR::psr(q,df=df,zeta=zeta,ope=ope)
	%pbeta(pv,shape1=np,shape2=1)
%}
%qmaxsr <- function(p,df,np,zeta=0,ope=1) {
	%pv <- qbeta(p,shape1=np,shape2=1)
	%SharpeR::qsr(pv,df=df,zeta=zeta,ope=ope)
%}
%@
%<<'beta_correction_test',echo=FALSE,eval=FALSE,cache=TRUE>>=
%# cumulative distribution of max of np independent SRs with SNR=zeta
%pmaxsr <- function(q,df,np,zeta=0,ope=1) {
	%pv <- SharpeR::psr(q,df=df,zeta=zeta,ope=ope)
	%# beta correction
	%pbeta(pv,shape1=np,shape2=1)
%}
%qmaxsr <- function(p,df,np,zeta=0,ope=1) {
	%# beta correction:
	%pv <- qbeta(p,shape1=np,shape2=1)
	%SharpeR::qsr(pv,df=df,zeta=zeta,ope=ope)
%}
%np <- 100
%zeta <- 0.02
%ope <- 1
%set.seed(1234)
%rvals <- replicate(10000,{
	%maxz <- max(SharpeR::rsr(np,df=df,zeta=zeta,ope=ope))
%})
%pvals <- pmaxsr(rvals,df=df,np=np,zeta=zeta,ope=ope)
%qmine <- function(p) { qmaxsr(p,df=df,np=np,zeta=zeta,ope=ope) }
%require(ggplot2)
%require(dplyr)
%data_frame(pvals=pvals) %>%
	%ggplot(aes(sample=pvals)) + 
	%stat_qq(distribution=qunif)
%data_frame(rvals=rvals) %>%
	%ggplot(aes(sample=rvals)) + 
	%stat_qq(distribution=qmine)
%@
%\vspace{-4mm}
%\emph{But:} 
	%Assume $\ssr[i]$ are independent, and $\psnr[i]$ are equal. Low power!
%%\begin{itemize}
%%\item 
%%\end{itemize}

%\end{frame}
%%UNFOLD


%\subsection{Intermezzo}

%% toss this test %FOLDUP
%\begin{frame}{California Doctor Says Throw This Test Out Now!}
%\vspace{-3mm}
%\begin{center}
	%\includegraphics[height=3.0in]{figure/31371m.jpg}
%\end{center}
%%\tiny \hspace{20mm} (apologies to Gary Larson)
%\end{frame}
%%UNFOLD

\section{Conditional Inference}
\subsection{Polyhedral Lemma}

% conditional estimation %FOLDUP
\begin{frame}[fragile]{Conditional Inference}
\emph{Idea:} perform inference only on the selected asset,
	conditioning on the selection criterion.\\

{\bf Polyhedral Lemma:} (\citet{lee2013exact})
	If $\vect{z} \sim \normlaw{\pvmu,\pvsig}$, 
	and you want to test $\trAB{\vect{\nu}}{\vect{z}}$ 
	conditional on $\AAA\vect{z}\le\bbb$:\\
$\trAB{\vect{\nu}}{\vect{z}}$ is a one-dimensional truncated normal:
$$
\trAB{\vect{\nu}}{\vect{z}} \sim \condtwo{\normlaw{\mu,\sigma^2}}{\,l \le \trAB{\vect{\nu}}{\vect{z}} \le h}.
$$

<<'plot_ellipse',echo=FALSE,eval=TRUE,cache=TRUE,fig.width=0.78*14,fig.height=0.27*14,out.width="0.78\\textwidth",out.height="0.27\\textwidth",dependson=c('plot_options')>>=
library(ggforce)
library(rlang)
library(gridExtra)
ph <- ggplot() 
for (iii in qnorm(ppoints(70))) { 
	if (iii > 0) {
		ph <- ph + geom_ellipse(aes(x0=1,y0=0.5,angle=15,fill='red',a=!!iii*5,b=!!iii*2),alpha=0.07,color=NA)
	}
}
theme_set(theme_minimal())
# theme_set(theme_minimal(base_size=12))
theme_update(legend.position="bottom")

if (require(viridis,quietly=TRUE)) {
  scale_colour_discrete <- function(...) {
    require(viridis,quietly=TRUE)
    scale_color_viridis(discrete=TRUE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
  scale_fill_discrete <- function(...) {
    require(viridis,quietly=TRUE)
    scale_fill_viridis(discrete=TRUE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
  # wait, can I also default for continuous cases?
  scale_colour_continuous <- function(...) {
    require(viridis,quietly=TRUE)
    scale_color_viridis(discrete=FALSE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
  scale_fill_continuous <- function(...) {
    require(viridis,quietly=TRUE)
    scale_fill_viridis(discrete=FALSE,end=0.85,option=VIRIDIS_COLOR_OPTION,...)
  }
}

ph1 <- ph  +
	guides(color=FALSE,alpha=FALSE,fill=FALSE) + 
	labs(title='Normal Density',
			 x='x',y='y',color=NULL,alpha=NULL)
course <- tibble::tribble(~x, ~y,
													-5,-1,
													-6,0.5,
													-5.5,2.2,
													-3,4.2,
													0.1,4.5,
													2.1,4.75,
													2.4,3,
													2,-1,
													0.5,-2,
													-5,-1)
ph2 <- ph  +
	geom_polygon(data=course,aes(x=x,y=y),fill='yellow',alpha=0.4) + 
	geom_path(data=course,aes(x=x,y=y),color='yellow',size=1.5) + 
	geom_abline(slope=1.3,intercept=0,linetype=3) + 
	geom_segment(aes(x=0,y=0,xend=2,yend=2*1.3),
							 arrow = arrow(length = unit(0.2, "cm"))) + 
	geom_point(aes(x=0,y=0),alpha=0.5) + 
	guides(color=FALSE,alpha=FALSE,fill=FALSE) + 
	labs(title='Normal Density with polytope',
			 x='x',y='y',color=NULL,alpha=NULL)
grid.arrange(ph1,ph2,ncol=2)
@


The ordering
$\ssr[(1)] \le \ssr[(2)], \ssr[(2)] \le \ssr[(3)], \ldots, \ssr[(\nstrat-1)] \le \ssr[(\nstrat)]$ is
of the form $\AAA\svsr\le\bbb$, 
we are performing inference on $\trbasev[(\nstrat)]{\pvsnr}$.






%Observe: when \RMAT is correlation of returns, then
	%\vspace{-2mm}
%\begin{equation}
%\svsr \approx 
%\normlaw{\pvsnr,\oneby{\ssiz}\wrapParens{\RMAT +
	%\frac{1}{2} \Mdiag{\pvsnr} \wrapParens{\RMAT\hadm\RMAT} \Mdiag{\pvsnr}}}.
%\label{eqn:apx_srdist_elliptical_again}
%\end{equation}
	%\vspace{-5mm}
%\begin{itemize}
%\item
%Max condition $\ssr[1] \ge \ssr[2], \ssr[1] \ge \ssr[3], \ldots$ can
%be expressed as $\AAA\svsr\le\bbb$.
%\item Inference on $\psnr[1]$ of the form $\trAB{\etav}{\pvsnr}$,
	%with $\etav=\basev[1]$.
%\end{itemize}
%Use results of Lee \etal \cite{lee2013exact},
%to perform conditional inference on $\trAB{\etav}{\yvec}$, with
%$\yvec\sim\normlaw{\pvmu,\pvsig}$ conditional on $\AAA\yvec\le\bbb$.\\
%\emph{Main idea}:
%``invert'' \chol{\pvsig} transform to get a normal $z$ linear in \yvec,
	%such that the conditional part restricts $z$ to a line segment, $\ccinterval{\Vmin}{\Vmax}.$\\
%Then get a p-value via
	%\vspace{-3mm}
%\begin{equation*}
%p = \frac{\pnorm[z] - \pnorm[\Vmin]}{\pnorm[\Vmax] - \pnorm[\Vmin]}.
%\end{equation*}
%Also use this to compute confidence intervals.


%\begin{itemize}
%\item Assume the $\ssr[i]$ are independent, and all $\psnr[i]$ are equal (to zero, say).
%\end{itemize}

\end{frame}
%UNFOLD

%\subsection{Simulations}

% conditional estimation %FOLDUP
%\begin{frame}[fragile]{Simulations}
%\vspace{-4mm}
<<'motherload_code',echo=FALSE,eval=TRUE,cache=TRUE>>=
# Lee et. al eqn (5.8)
F_fnc <- function(x,a,b,mu=0,sigmasq=1) {
  sigma <- sqrt(sigmasq)
  phis <- pnorm((c(x,a,b)-mu)/sigma)
  (phis[1] - phis[2]) / (phis[3] - phis[2])
}
# Lee eqns (5.4), (5.5), (5.6)
Vfuncs <- function(z,A,b,ccc) {
  Az <- A %*% z
  Ac <- A %*% ccc
  bres <- b - Az
  brat <- bres
  brat[Ac!=0] <- brat[Ac!=0] / Ac[Ac!=0]
  Vminus <- max(brat[Ac < 0])
  Vplus  <- min(brat[Ac > 0])
  Vzero  <- min(bres[Ac == 0])
  list(Vminus=Vminus,Vplus=Vplus,Vzero=Vzero)
}
# Lee et. al eqn (5.9)
ptn <- function(y,A,b,nu,mu,Sigma,numu=as.numeric(t(nu) %*% mu)) {
  Signu <- Sigma %*% nu
  nuSnu <- as.numeric(t(nu) %*% Signu)
  ccc <- Signu / nuSnu  # eqn (5.3)
  nuy <- as.numeric(t(nu) %*% y)
  zzz <- y - ccc * nuy  # eqn (5.2)
  Vfs <- Vfuncs(zzz,A,b,ccc)
  F_fnc(x=nuy,a=Vfs$Vminus,b=Vfs$Vplus,mu=numu,sigmasq=nuSnu)
}
# invert the ptn function to find y at a given pval.
qtn <- function(p,A,b,nu,mu,Sigma,numu=as.numeric(t(nu) %*% mu),intvl=c(-10,10)) {
	f <- function(y) {ptn(y,A,b,nu=nu,mu=mu,Sigma=Sigma,numu=numu) - p}
	trypnts <- seq(from=min(intvl),to=max(intvl),length.out=101)
	ys <- sapply(trypnts,f)
	dsy <- diff(sign(ys))
	if (any(dsy < 0)) {
		widx <- which(dsy < 0)
		intvl <- trypnts[widx + c(0,1)]
	}
  uniroot(f=f,interval=intvl,extendInt='yes')$root
}
# invert the ptn function to find nu'mu at a given pval.
citn <- function(p,y,A,b,nu,Sigma) { 
  Signu <- Sigma %*% nu
  nuSnu <- as.numeric(t(nu) %*% Signu)
  ccc <- Signu / nuSnu  # eqn (5.3)
  nuy <- as.numeric(t(nu) %*% y)
  zzz <- y - ccc * nuy  # eqn (5.2)
  Vfs <- Vfuncs(zzz,A,b,ccc)

  # you want this, but there are numerical issues: 
  #f <- function(numu) { F_fnc(x=nuy,a=Vfs$Vminus,b=Vfs$Vplus,mu=numu,sigmasq=nuSnu) - p } 
  sigma <- sqrt(nuSnu)
  f <- function(numu) { 
    phis <- pnorm((c(nuy,Vfs$Vminus,Vfs$Vplus)-numu)/sigma)
    #(phis[1] - phis[2]) - p * (phis[3] - phis[2])
    phis[1] - (1-p) * phis[2] - p * phis[3]
  }
  # this fails sometimes, so find a better interval
  intvl <- c(-1,1)  # a hack.
  # this is very unfortunate
    trypnts <- seq(from=min(y),to=max(y),length.out=31)
    ys <- sapply(trypnts,f)
    dsy <- diff(sign(ys))
    if (any(dsy < 0)) {
      widx <- which(dsy < 0)
      intvl <- trypnts[widx + c(0,1)]
    } else {
      maby <- 2 * (0.1 + max(abs(y)))
      trypnts <- seq(from=-maby,to=maby,length.out=31)
      ys <- sapply(trypnts,f)
      dsy <- diff(sign(ys))
      if (any(dsy < 0)) {
        widx <- which(dsy < 0)
        intvl <- trypnts[widx + c(0,1)]
      }
    }
  uniroot(f=f,interval=intvl,extendInt='yes')$root
}
@
<<'motherload_sims',echo=FALSE,eval=TRUE,cache=TRUE>>=
R <- pmin(diag(100) + 0.7,1)  # mutual correlation of 0.7
mu <- seq(-0.1,0.1,length.out=nrow(R))
set.seed(1234)
simvals <- replicate(250,{
	X <- mvtnorm::rmvnorm(n=5*252,mean=mu,sigma=R)
	max(colMeans(X) / apply(X,2,sd))
})
@
<<'motherload_sims_hidden',echo=FALSE,eval=TRUE,cache=TRUE>>=
# 3f7d255b-0ef1-48f8-be8d-b629b1146415 
p <- length(mu)
zeta <- mu / diag(R)
mymu <- zeta
nday <- 5*252
mySigma <- (1/nday) * (R + (1/2) * diag(zeta) %*% (R * R) %*% diag(zeta))

A1 <- cbind(-1,diag(p-1))
set.seed(1234)
ce_pvals <- replicate(length(simvals),{
	X <- mvtnorm::rmvnorm(nday,mean=mu,sigma=R)
	zeta <- colMeans(X) / apply(X,2,sd)
	y <- zeta

  # collect the maximum, so reorder the A above
  yord <- order(y,decreasing=TRUE)
  revo <- seq_len(p)
  revo[yord] <- revo

  A <- A1[,revo]
  nu <- rep(0,p)
  nu[yord[1]] <- 1
  b <- rep(0,p-1)

  foo <- ptn(y=y,A=A,b=b,nu=nu,mu=mymu,Sigma=mySigma)
})
@
%\vspace{-3mm}
<<'motherload_sims_hidden_plotz',echo=FALSE,eval=FALSE,cache=TRUE,fig.width=0.75*10,fig.height=0.3*10,out.width="0.75\\textwidth",out.height="0.3\\textwidth">>=
# f35bffb6-d645-4cfe-b893-d2be10a2201f 
# cdf & qtile, max of np independent SRs, SNR=zeta
pmaxsr <- function(q,df,np,zeta=0,ope=1) {
	pv <- SharpeR::psr(q,df=df,zeta=zeta,ope=ope)
	pbeta(pv,shape1=np,shape2=1)
}
qmaxsr <- function(p,df,np,zeta=0,ope=1) {
	pv <- qbeta(p,shape1=np,shape2=1)
	SharpeR::qsr(pv,df=df,zeta=zeta,ope=ope)
}

suppressMessages({
	library(dplyr)
	library(ggplot2)
})
#plot(ecdf(ce_pvals))
# the 1 - takes care of lower.tail=FALSE
mht_pvals <- 1 - pmaxsr(simvals,df=nday-1,np=p,zeta=max(zeta),ope=1)
#plot(ecdf(mht_pvals))
#plot(simvals,mht_pvals)
data_frame(simvals=simvals,mht_pvals=mht_pvals,ce_pvals) %>%
	tidyr::gather(key=proc,value=pvalue,mht_pvals,ce_pvals) %>%
	mutate(procedure=case_when(grepl('^mht_',proc)   ~ 'MHT',
														 grepl('^ce_',proc)    ~ 'Conditional Estimation')) %>%
	mutate(procedure=forcats::fct_rev(factor(procedure))) %>%
	ggplot(aes(sample=pvalue)) + 
	stat_qq(distribution=qunif,alpha=0.15) +
	stat_qq_line(distribution=qunif,color='red') +
	facet_grid(.~procedure)

@

%\end{frame}
%UNFOLD

\subsection{Conditional Inference on the \txtSNR}
% conditional estimation %FOLDUP
\begin{frame}[fragile]{Conditional Inference Procedure}
Use the polyhedral lemma to test
$\Hyp[0] : \psnr[(\nstrat)] = \psnr[0]$.

\emph{Pro:}
\begin{itemize}
\item 
Inference only operates on \psnr[(\nstrat)], ignores $\psnr[(1)],\psnr[(2)],\ldots,\psnr[(\nstrat-1)]$.
\item
Takes into account correlation of returns.\\
	Together these give higher power.
\item
	The \RMAT need not be positive definite, so in theory this works for $\ssiz \ll\nstrat$.
\end{itemize}
	\emph{Con:}
\begin{itemize}
\item 
	Have to estimate the covariance of \svsr.
\item
The normal approximation $\svsr \approx \normlaw{\cdots}$ may not be good enough.
\item
If $\ssr[(\nstrat)] \approx \ssr[(\nstrat-1)]$, will not take into account
	that you would have selected strategy $(\nstrat-1)$.
\end{itemize}

\end{frame}
%UNFOLD

\subsection{Simulations}

\begin{frame}[fragile]{Simulations}
Test power under the alternative:
\begin{itemize}
	\item Let $m$ strategies have $\psnr=c>0$, and $\nstrat-m$ have $\psnr=-c$.\\
		Test for $m=\nstrat,\nstrat/2,1$.
		Vary $c$.
	\item 
		Measure the rejection probability versus the \txtSNR of strategy
		$(\nstrat)$. (Will be $\pm c$.)
\end{itemize}

<<'motherload_sim_funcs',echo=FALSE,eval=TRUE,cache=TRUE>>=
suppressMessages({
	library(dplyr)
  library(doFuture)
  library(epsiwal)
})

tgen <- function(n,mu,sigma,df) {
  rescal <- sqrt((df-2)/df)
  rescal * mvtnorm::rmvt(n,df=df,delta=mu/rescal,sigma=sigma,type='shifted')
}

dosim <- function(nsim,nday,R,mu,testmu=mu,ret_dist=c('gaussian','t4','t5','t6','t20'),
                  estimate_parms=FALSE,higher_order=FALSE) { 
	ret_dist <- match.arg(ret_dist)
  p <- length(mu)
  zeta <- mu / diag(R)
  if (!estimate_parms) {
    if (higher_order) {
      kapp <- switch(ret_dist,
                     gaussian=1,
                     t4=Inf,
                     t5=3,
                     t6=2,
                     t20=18/16)
      mySigma <- (1/nday) * (R + ((kapp-1)/4) * outer(zeta,zeta,'*') + (kapp/2) * diag(zeta) %*% (R * R) %*% diag(zeta))
    } else {
      mySigma <- (1/nday) * (R + (1/2) * diag(zeta) %*% (R * R) %*% diag(zeta))
    }
  }

  testzeta <- testmu / diag(R)
  generator <- switch(ret_dist,
                      gaussian=function(n) mvtnorm::rmvnorm(n,mean=mu,sigma=R),
                      t4=function(n) tgen(n,mu=mu,sigma=R,df=4),
                      t5=function(n) tgen(n,mu=mu,sigma=R,df=5),
                      t6=function(n) tgen(n,mu=mu,sigma=R,df=6),
                      t20=function(n) tgen(n,mu=mu,sigma=R,df=20))

  A1 <- cbind(-1,diag(p-1))
  these_sims <- replicate(nsim,{
    X <- generator(nday)
    srs <- colMeans(X) / apply(X,2,sd)

    if (estimate_parms) {
      Rhat <- cov2cor(cov(X))
      if (higher_order) {
        kapp <- median(apply(X,2,moments::kurtosis)) / 3
        mySigma <- (1/nday) * (Rhat + ((kapp-1)/4) * outer(srs,srs,'*') + (kapp/2) * diag(srs) %*% (Rhat * Rhat) %*% diag(srs))
      } else {
        mySigma <- (1/nday) * (Rhat + (1/2) * diag(srs) %*% (Rhat * Rhat) %*% diag(srs))
      }
    }

    y <- srs

    # collect the maximum, so reorder the A above
    yord <- order(y,decreasing=TRUE)
    revo <- seq_len(p)
    revo[yord] <- revo

    A <- A1[,revo]
    nu <- rep(0,p)
    nu[yord[1]] <- 1
    b <- rep(0,p-1)

    foo <- epsiwal::pconnorm(y=y,A=A,b=b,eta=nu,mu=testzeta,Sigma=mySigma)
    c(max(srs),foo,zeta[yord[1]])
  })
  data_frame(simvals=as.numeric(these_sims[1,]),
             pvals=as.numeric(these_sims[2,]),
             popvals=as.numeric(these_sims[3,]))
}
multsim <- function(nsim,nday,R,mu,testmu=mu,estimate_parms=FALSE,ret_dist='gaussian',higher_order=FALSE,splitby=32) { 
  if ((nsim > 2*splitby) && require(future.apply,quietly=TRUE)) {
    # do in parallel.
    nper <- table(1 + ((0:(nsim-1) %% splitby))) 
    retv <- future_lapply(nper,
                          dosim,
                          nday=nday,R=R,mu=mu,testmu=testmu,ret_dist=ret_dist,
                          estimate_parms=estimate_parms,higher_order=higher_order) %>%
      bind_rows()
  } else {
    retv <- dosim(nsim=nsim,nday=nday,R=R,mu=mu,testmu=testmu,ret_dist=ret_dist,
            estimate_parms=estimate_parms,higher_order=higher_order)
  }
  retv
}
parsim <- function(nsim,nday,R,mu,testmu=mu,estimate_parms=FALSE,ret_dist='gaussian',higher_order=FALSE,nnodes=7) {
  plan(multicore, workers=nnodes)
  retv <- multsim(nsim=nsim,nday=nday,R=R,
                  mu=mu,testmu=testmu,
                  estimate_parms=estimate_parms,
                  ret_dist=ret_dist,
                  higher_order=higher_order)
  plan(sequential)
  retv
}
ks_sim <- function(rho,nday,nstrat,max_zeta,estimate_parms=FALSE,ret_dist='gaussian',higher_order=FALSE,nsim=100) {
  R <- pmin(diag(nstrat) + rho,1)  
  mu <- seq(0,max_zeta,length.out=nrow(R))
  sim <- parsim(nsim,nday=nday,R=R,mu=mu,ret_dist=ret_dist,
                estimate_parms=estimate_parms,higher_order=higher_order)
  broom::tidy(ks.test(sim$pvals,punif))
}
#sim <- parsim(nsim,nday=nday,R=R,mu=mu,estimate_parms=FALSE,ret_dist='t5')
#plot(ecdf(sim$pvals))

chib_test <- function(xbar2,nstrat,lower.tail=FALSE) {
  cwts <- exp(lchoose(nstrat,0:nstrat) - nstrat * log(2))
  okwt <- (cwts > 1e-9)
  sbdf <- which(okwt) - 1
  sbwt <- cwts[okwt]
  # should check that sum(sbwt) is around 1
  #stopifnot(abs(sum(sbwt) - 1) < 1e-5)
  sum(sbwt * pchisq(xbar2,df=sbdf,lower.tail=lower.tail))
}
# call a bunch of testing procedures
alt_test <- function(nday,mu,nsim=100,rho=0,psnr0=0) {
  nstrat <- length(mu)
  R <- pmin(diag(nstrat) + rho,1)  
  kurty <- 1.0 # assumed

	apart <- sqrt(nday)/sqrt(1-rho)
	bpart <- sqrt(nday) * ((1/sqrt(1-rho+nstrat*rho)) - (1/sqrt(1-rho)))

  # weights from chi-bar square distro
  cwts <- exp(lchoose(nstrat,0:nstrat) - nstrat * log(2))
  okwt <- (cwts > 1e-9)
  sbdf <- which(okwt) - 1
  sbwt <- cwts[okwt]
  # should check that sum(sbwt) is around 1
  stopifnot(abs(sum(sbwt) - 1) < 1e-5)
  cval <- 1/sqrt(1 + (nstrat-1) * rho)
  dval <- sqrt(1-rho)
  xi0 <- cval * psnr0

  # follman's, and redundant to above
  a0 <- (1-rho) + (kurty/2) * psnr0^2 * (1-rho^2)
  a2 <- rho + ((kurty-1)/4) * psnr0^2 + (kurty/2) * psnr0^2 * rho^2
  b0 <- 1 / sqrt(a0)
  #b2 <- (-1 / (nstrat*sqrt(a0))) + (1/nstrat) / sqrt(a0 + nstrat*a2)
  #cval <- b0 + nstrat * b2

  f1 <- nday * nstrat * cval^2
  f2 <- nday * b0^2

  # Hansens cutoff
  spcut <- xi0 - sqrt(2*log(log(nday))/nday)

  # would be great to parallelize this with future_replicate?
  mhtpvals <- replicate(nsim,{
    if (rho == 0) {
      svsr <- SharpeR::rsr(n=nstrat,df=nday-1,zeta=mu,ope=1)
    } else {
      X <- mvtnorm::rmvnorm(nday,mean=mu,sigma=R)
      svsr <- colMeans(X) / apply(X,2,sd)
    }
    xm <- which.max(svsr)
    ssravg <- mean(svsr)
    ssrmax <- max(svsr)

    # this is uncorrected bonferroni p-value, FWIW.
		bonf_pval <- nstrat * SharpeR::psr(ssrmax,df=nday-1,zeta=psnr0,ope=1,lower.tail=FALSE) 

		# do the correction
		corr_stat <- apart * ssrmax + bpart * ssravg
		corr_pval <- nstrat * pnorm(corr_stat,lower.tail=FALSE)

    # convert to 'xi'
    xi <- cval * ssravg + (svsr-ssravg) / dval

    # chibarsquare test, assuming rho=0
    chibs <- (nday) * sum(pmax(xi - xi0,0)^2)
    chibp <- sum(sbwt * pchisq(chibs,df=sbdf,lower.tail=FALSE))

    # follman test
    g2 <- f1 * (ssravg - psnr0)^2 + f2 * sum((svsr - ssravg)^2)
    follp <- pchisq(g2,df=nstrat,lower.tail=FALSE)
    ffollp <- ifelse(ssravg > psnr0,0.5 * follp,1 - 0.5*follp)

    # hansens procedures; 
    nabove <- sum(xi > spcut)
    # chibar-square with loglog adjustment
    llval <- ifelse(nabove > 0,chib_test(chibs,nabove,lower.tail=FALSE),1)
    # bonferroni/SPA p-value, correcting the rho-safe Bonferroni above
    spval <- ifelse(nabove > 0,(nabove/nstrat) * corr_pval,1)

    c(bonf_pval,corr_pval,chibp,ffollp,llval,spval,mu[xm])
  })
  retv <- data.frame(t(mhtpvals)) %>%
    setNames(c('norho_mht','mht','chibarsquare','follman','loglog','spa','popvals')) %>%
    tidyr::gather(key=method,value=pvals,-popvals)

  retv
}
mult_alt_test <- function(nday,mu,nsim=100,rho=0,psnr0=0,splitby=64) {
  if ((nsim > 2*splitby) && require(future.apply,quietly=TRUE)) {
    # do in parallel.
    nper <- table(1 + ((0:(nsim-1) %% splitby))) 
    retv <- future_lapply(nper,
                          alt_test,
                          nday=nday,mu=mu,rho=rho,psnr0=psnr0) %>%
      bind_rows()
  } else {
    retv <- alt_test(nsim=nsim,nday=nday,mu=mu,rho=rho,psnr0=psnr0) 
  }
  retv
}

par_alt_test <- function(nday,mu,nsim=100,rho=0,psnr0=0,nnodes=7) {
  plan(multicore, workers=nnodes)
  retv <- mult_alt_test(nday=nday,mu=mu,
                        nsim=nsim,rho=rho,
                        psnr0=psnr0)
  plan(sequential)
  retv
}
# spawn mu and call the sims
bot_rawsim <- function(nday,nstrat,one_zeta=0,nsim=100,rho=0,
                       do_conde=TRUE,
                       mutype=c('equal','onegood','halfgood','spread')) {
	mutype <- match.arg(mutype)
  mu <- switch(mutype,
               equal=rep(one_zeta,nstrat),
               onegood=c(one_zeta,rep(-one_zeta,nstrat-1)),
               halfgood=c(rep(one_zeta,floor(nstrat/2)),
                          rep(-one_zeta,ceiling(nstrat/2))),
               spread=seq(-one_zeta,one_zeta,length.out=nstrat))
  retv <- par_alt_test(nday=nday,mu=mu,nsim=nsim,rho=rho)
  if (do_conde) {
    R <- pmin(diag(nstrat) + rho,1)  
    retv <- bind_rows(parsim(nsim=nsim,nday=nday,R=R,mu=mu,testmu=rep(0,nstrat)) %>%
                      select(-simvals) %>% 
                      mutate(pvals=1-pvals) %>% 
                      mutate(method='condest'),
                    retv)
  }
  retv
}
# compute the rejection rates
mhtsim <- function(alpha=0.05,...) {
  bot_rawsim(...) %>%
    group_by(method,popvals) %>%
      summarize(rej_rate=mean(pvals < alpha),
                tot_base=n()) %>%
    ungroup() %>%
    arrange(method,popvals)
}
@
<<'sims_vs_mht',dependson=c('motherload_sim_funcs'),echo=FALSE,eval=TRUE,cache=TRUE>>=
# 6cbe48d8-9b1f-4b5e-a439-228082a8a4b4 
suppressMessages({
  library(tidyr)
  library(dplyr)
  library(future)
})

FINAL.VERSION <- TRUE
# actual run the sims
lout <- ifelse(FINAL.VERSION,15,9)
params <- data_frame(one_zeta=seq(0,0.15,length.out=lout)) %>%
  tidyr::crossing(data_frame(mutype=c('onegood','halfgood','equal'))) 

mht_nsim <- ifelse(FINAL.VERSION,1e4,1e3)
mht_nday <- ifelse(FINAL.VERSION,4*252,2*252)
mht_nstrat <- ifelse(FINAL.VERSION,50,24)

registerDoFuture()
plan(multicore,workers=7)
set.seed(1234)
#system.time({
resu <- params %>%
  group_by(one_zeta,mutype) %>%
    summarize(resu=list(mhtsim(nday=mht_nday,nstrat=mht_nstrat,one_zeta=one_zeta,nsim=mht_nsim,mutype=mutype))) %>%
  ungroup() %>%
  unnest()
#})
plan(sequential)
@

<<'power_plotz_one',dependson=c('sims_vs_mht','plot_options'),echo=FALSE,eval=TRUE,cache=TRUE,fig.width=0.87*10,fig.height=0.35*10,out.width="0.87\\textwidth",out.height="0.35\\textwidth">>=
fig_cap <- paste0('The empirical power of the conditional estimation, MHT corrected test, ',
                  "Follman's test, ",
                  "the chi-bar-square test, ",
                  "and the chi-bar-square and MHT tests with Hansen's $\\log\\log$ correction ",
                  "are shown versus the \\txtSNR of the asset with maximum \\txtSR under ",
                  'different arrangements of the vector \\pvsnr. ',
                  'We jitter the points horizontally to distinguish tests with very similar rejection rates. ')

library(ggplot2)
set.seed(1234)
ph <- resu %>%
  filter(method!='norho_mht') %>%  # we are using rho=0, so should be the same
  #filter(method!='follman') %>%  # simplify
  mutate(shapel=case_when(grepl('^condest$',method)   ~ 'cond. est.',
                          grepl('^mht|spa$',method)   ~ 'MHT',
                          grepl('^(chibarsquare|loglog)$',method)  ~ 'chi-bar^2',
                          grepl('^follman$',method)   ~ 'Follman',
                          TRUE ~ 'ERROR')) %>%
  mutate(method=case_when(grepl('^condest$',method)   ~ 'cond. est.',
                          grepl('^mht$',method)       ~ 'MHT',
                          grepl('^chibarsquare$',method)  ~ 'chi-bar^2',
                          grepl('^follman$',method)   ~ 'Follman',
                          grepl('^loglog$',method)    ~ 'Hansen chi-bar^2',
                          grepl('^spa$',method)       ~ 'Hansen SPA',
                          TRUE ~ 'ERROR')) %>%
  mutate(mutype=case_when(mutype=='equal'     ~ 'all-equal',
                          mutype=='halfgood'  ~ 'half-good',
                          mutype=='onegood'   ~ 'one-good',
                          TRUE ~ 'ERROR')) %>%
  mutate(lt=ifelse(grepl('Hansen',method),'yes','no')) %>%
	filter(method %in% c('MHT','Hansen SPA','cond. est.')) %>%
	mutate(method=gsub('Hansen SPA','MHT + Hansen loglog',method)) %>%
	mutate(snr=sqrt(252)*popvals) %>%
  ggplot(aes(snr,rej_rate,color=method)) + # ,linetype=lt))  +
  geom_line(alpha=0.8) + geom_jitter(aes(shape=method),height=0,width=0.001) + 
  facet_grid(.~mutype) + 
  geom_hline(yintercept=0.05,linetype=2,alpha=0.5) + 
  geom_vline(xintercept=0,linetype=2,alpha=0.3) + 
  scale_y_continuous(labels=scales::percent) + 
  labs(x='signal noise ratio',
       y='rejection rate at nominal 0.05 level',
       color='method',
       shape='method', #shape='statistic',
       #linetype='Hansen correction?',
       title='Rejection rate of tests')
print(ph)
@
\end{frame}


\nocite{student08ttest}
\subsection{Conclusion}
\begin{frame}{Conclusion}%FOLDUP

Future directions:
\begin{itemize}
\item Strategies are often selected based on in-sample fitting, so that
	$\ssr^2$ follows a $\chi^2$ distribution.\\
	What is the polyhedral lemma for correlated $\chi^2$ variates?
\item Can we adapt Conditional Inference to test 
\begin{equation*}
  \label{hyp:more_max_snr_conditional}
  \Hyp[0] : \psnr[(\nstrat)] = \psnr[(\nstrat-1)] = \ldots = \psnr[(\nstrat-m)] = \psnr[0]\quad\mbox{versus}\quad \Hyp[1] : \psnr[(\nstrat)] \vee 
	\psnr[(\nstrat-1)] \vee
	\ldots
	\psnr[(\nstrat-m)] > \psnr[0].
\end{equation*}
\item Where else can we use Hansen's loglog trick?
\end{itemize}

Learn more:
\begin{itemize}
\item \emph{Conditional inference on the asset with maximum Sharpe ratio}.  \cite{pav2019maxsharpe}
\item \emph{The Sharpe Ratio: Statistics and Applications}.  \cite{pav_the_book}
\end{itemize}
\end{frame}%UNFOLD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Appendix}%FOLDUP
\subsection{Bibliography}
\begin{frame}[allowframebreaks]{Bibliography}%FOLDUP
	\begin{columns}
		\begin{column}{0.69\textwidth}

%bibliography%FOLDUP
%%generate the rauto.bib bitex file%FOLDUP
%see also
%http://r.789695.n4.nabble.com/Automating-citations-in-Sweave-td872079.html
<<gen_bibliography,echo=FALSE>>=
FID <- file("rauto.bib", "w")  # open an output file connection

cite.by.name <- function(x){ 
	res <- toBibtex(citation(x)) 
	if (is.list(res)) res <- res[[1]] 
	res[1] <- sub("{",paste("{",x,sep=''),res[1],fixed=TRUE) 
	#2FIX: multiple citations; bleah;
	cat(res,file = FID, sep = "\n")
	return(NULL)
} 
z <- sapply( .packages(TRUE), function(x) try( cite.by.name(x) ) )
close(FID)
@
%UNFOLD
\def\newblock{\hskip .11em plus .33em minus .07em} % important!
\bibliographystyle{plainnat}
\tiny{
\bibliography{common,rauto}}
%UNFOLD

		\end{column}
		\begin{column}{0.25\textwidth}
			September 2021:\\
			\includegraphics[width=\textwidth]{media/Screenshot_20210320_152917.png}
		\end{column}
	\end{columns}
\end{frame}%UNFOLD

%\begin{frame}[allowframebreaks]{Common Questions}
%%FOLDUP
%\begin{exampleblock}{Why another AD package?}
%I needed it for the multivariate delta method, and suspected that
%numerical approximations would be too slow.
%\end{exampleblock}
%\begin{exampleblock}{Can it compute Hessians or higher order derivatives?}
%Not yet. That would be very complicated. You might be better off using
%the \ndpack package.
%\end{exampleblock}
%\begin{exampleblock}{How are derivatives computed?}
%I took a `high level' approach, overloading as many methods as possible.
%A `low level' approach that overloads only addition, multiplication, 
%exponentiation, and so on, would not work for computations performed in
%\eg C or C++ code.
%\end{exampleblock}
%\begin{exampleblock}{I am getting an error.}
%Not everything works yet. File an issue on github.
%In the interim, you can use the
%\texttt{madness::numderiv} method for numerical approximation, or 
%instead use 
%the \ndpack package.
%\end{exampleblock}
%\begin{exampleblock}{What about symmetry?}
%The \texttt{twomoments} and \texttt{theta} methods deal with
%symmetry correctly. Be wary about constructing your own
%\madobj objects where the matrix must be symmetric. To `force'
%matrix symmetry, use \eg \\
%\texttt{forcesym <- function(x) \{ 0.5 * (x+t(x)) \}}.
%\end{exampleblock}

%%UNFOLD
%\end{frame}

%\end{frame}
%%UNFOLD


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
%for vim modeline: (do not edit)
% vim:ts=2:sw=2:tw=79:fdm=marker:fmr=FOLDUP,UNFOLD:cms=%%s:syn=rnoweb:ft=rnoweb:ai:si:cin:nu:cole=0:fo=croql:cino=p0t0c5(0:
